# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50b225b7482d30a7a7c6b3a858cbec38f300a4dae456896f09f3012a406d6184dd43208ecb358bb6883e25eb6775aba76fa3b067b3cd5d286040af3ae847928c

test:
  secret_key_base: 24951a93e5efae56092be1575cae95ad9c992eb9821083a1c66f8f762a7c6b6b8f0a522bac7d8ee3f25d3f6597e63427128ed985cd1d3addb31fc59d670a664b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
